#!/usr/bin/env bash
# The size-versus-declared-width curve (M3-T5, for D-0028).
#
# Generates D-0028's shape -- two variables declared 0..w, one row demanding 5w/2,
# which is infeasible on the declared bounds, so the solver refutes it at the root
# having pruned NOTHING -- at each width given, and hands the models to run_bench.sh.
#
# The models are written to a temporary directory and deleted afterwards. They are
# deliberately NOT added to test/models/: only the w = 999 member of this family is
# committed (test/models/width_root_unsat.fzn, M1-T30), because the gate pays for
# every model on every run and w = 999 is where the effect becomes unmistakable for
# about 50 ms. This script is the on-demand way to see the rest of the curve.
#
# CEILING, and why it is where it is. This machine has ~15 GB of RAM and several
# sessions compiling on it at once, and the in-memory cost of this shape is far above
# its file size: about 1.5 kB of peak RSS per unit of declared width against 63 bytes
# of .opb (measured, bench/README.md). w = 10^6 is a 156 MB .opb and roughly 2.8 GB of
# RSS to produce it, and an agent OOMed this box during this very round. So:
#
#   * run_bench.sh's guard refuses any declared width above 100000 outright;
#   * the widths here default to 9 .. 9999, which costs well under a second each;
#   * every invocation is under a `timeout` (run_bench.sh -t);
#   * anything past the default set is a deliberate act, one width at a time, on an
#     idle machine -- and D-0028 already has the 10^5 and 10^6 rows measured, so
#     re-running them buys nothing but risk.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WIDTHS=(9 99 999 9999)
[ "$#" -gt 0 ] && WIDTHS=("$@")

DIR="$(mktemp -d -t baguette-width-XXXXXX)"
trap 'rm -rf "${DIR}"' EXIT

declare -a MODELS=()
for w in "${WIDTHS[@]}"; do
  if ! [[ "${w}" =~ ^[0-9]+$ ]]; then
    echo "width_curve.sh: '${w}' is not a width" >&2
    exit 2
  fi
  rhs=$(( (5 * w) / 2 ))
  f="${DIR}/width_${w}.fzn"
  {
    printf '%% D-0028 shape at w = %s, generated by bench/width_curve.sh. Not a test model.\n' "${w}"
    printf 'array [1..2] of int: coeffs = [1, 1];\n'
    printf 'var 0..%s: a :: output_var;\n' "${w}"
    printf 'var 0..%s: b :: output_var;\n' "${w}"
    printf 'constraint int_lin_eq(coeffs, [a, b], %s);\n' "${rhs}"
    printf 'solve satisfy;\n'
  } > "${f}"
  MODELS+=("${f}")
done

echo "width curve: w = ${WIDTHS[*]}"
echo "  shape: two vars 0..w, one row demanding 5w/2 -- infeasible on the declared"
echo "  bounds, so zero prunings and zero decisions. Everything in the .pbp is the"
echo "  single weakening-chain justification. D-0028."
echo
# The positional arguments are widths, not benchmark options; extra options for
# run_bench.sh go in BENCH_ARGS, e.g. BENCH_ARGS='-r 9' bench/width_curve.sh 999
# shellcheck disable=SC2086
exec "${ROOT}/bench/run_bench.sh" -t 120 ${BENCH_ARGS:-} "${MODELS[@]}"
